development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: cafeauchain-backend_development
  pool:     5
  username: postgres
  password: password
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: cafeauchain-backend_test
  pool:     5
  username: postgres
  password: password
  template: template0

demo:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  template: template0
  pool:     5
  encoding: unicode

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  template: template0
  pool:     5
  encoding: unicode