development:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: example.com
  secret_key_base: 3acd5af8366ecaea7bf0fe6153442bacf3aff483386220258f0938aa1ee30e850236f48dc0bcbd8b330876f7074bd4b95a0b5e2ba2962a47bdfbb5dec1011bff
  host: <%= ENV["MULTICHAIN_HOST"] %>

test:
  secret_key_base: cfce6d2294d5c9704e9c73ec5d2e6591fee78ca7579a4f3e3856fb09cdb1930cbe140e1e205b6da3577bca17f02f2fd0363b86d59b1ddab7efb3160ec79af8c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host: <%= ENV["MULTICHAIN_HOST"] %>